import type { Species, Stage } from './types';
export const CHAPTERS = [
 { name: 'Kapka, která si pamatuje', short: 'Mikrosvět', title: 'První nádech života', subtitle: 'V prachu světla se rodí tvoje linie.', instruction: 'Jez, prozkoumej tři niky a vytvoř dvě nové generace. Pak vyhledej proud do útesů.', meals: 24, color: '#a9e8bf' },
 { name: 'Zahrady pod přílivem', short: 'Útesy a mělčiny', title: 'Tělo pro nový svět', subtitle: 'Pod hladinou není nikdo sám.', instruction: 'Poznej tři vodní niky, nasyť linii a dvakrát se rozmnož. Pro souš si vyviň plíce a končetiny.', meals: 36, color: '#84dbe6' },
 { name: 'Paměť vyschlého moře', short: 'Pobřeží a souš', title: 'Zanech po sobě život', subtitle: 'Příliv odchází. Rozhodni, co zůstane.', instruction: 'Zachraň tři prameny, zastav invazní žrouty nebo převeď symbiotickou linii do svatyně.', meals: 0, color: '#f1cf8e' },
];
export const PATCH_NAMES = [
 [['Světelná zahrada','Řasy · klidná voda'],['Skleněný vír','Minerály · silné proudy'],['Soumraková kolébka','Detrit · stín a partneři']],
 [['Korálové varhany','Nektar · členitý úkryt'],['Les plovoucích stuh','Řasy · svislý prostor'],['Noční průduchy','Minerály · temnota a proud']],
 [['Přílivové sady','Nektar · úrodná pobřežní nika'],['Jantarové terasy','Skalní překážky · suchý vítr'],['Zahrada posledního deště','Detrit · chlad a symbióza']],
];
export const SPECIES: Species[] = [
 {id:'veil',name:'Závojník',stage:0,role:'grazer',shape:'ray',color:0x96dab9,size:.65,speed:3.0,diet:['algae'],description:'Filtruje světelnou řasu. Před lovci klesá ke dnu.'},
 {id:'needle',name:'Jehloúst',stage:0,role:'predator',shape:'stalker',color:0xd58478,size:.85,speed:4.0,diet:['meat'],description:'Hledá hladové a osamělé závojníky. Před výpadem zamíří; úhyb nebo kámen přeruší lov.'},
 {id:'lantern',name:'Lucernička',stage:0,role:'partner',shape:'jelly',color:0xefbf85,size:.55,speed:2.2,diet:['detritus'],description:'Světelný partner. Rozšíří smysly, ale spotřebovává potravu.'},
 {id:'sail',name:'Plachtovec',stage:1,role:'grazer',shape:'spiral',color:0x7ccbb1,size:1.0,speed:3.8,diet:['algae','nectar'],description:'Pase se ve stuhovém lese. Ve volné vodě je zranitelný.'},
 {id:'ribbon',name:'Stužkohrot',stage:1,role:'predator',shape:'stalker',color:0xca8eaf,size:1.3,speed:5.0,diet:['meat'],description:'Hlídkuje kolem korálů a loví hladové plachtovce.'},
 {id:'mender',name:'Štítojem',stage:1,role:'partner',shape:'crab',color:0xe5bd81,size:.8,speed:2.6,diet:['mineral','detritus'],description:'Štítový partner s tvrdou schránkou. Udržuj ho sytého.'},
 {id:'bell',name:'Zvonkonoš',stage:2,role:'grazer',shape:'strider',color:0xa8bf89,size:1.1,speed:3.4,diet:['nectar','algae'],description:'Na pružných nohách následuje úrodné prameny.'},
 {id:'gloom',name:'Prachokřídlík',stage:2,role:'partner',shape:'moth',color:0xaf9adb,size:.8,speed:3.0,diet:['detritus','nectar'],description:'Recykluje zbytky. Potřebuje potravu a vodu pro své spory.'},
 {id:'gnaw',name:'Žrout pramenů',stage:2,role:'invasive',shape:'worm',color:0xc78465,size:1.1,speed:2.8,diet:['algae','nectar','detritus'],description:'Přemnožený býložravec vyčerpává půdu. Lov obnovuje prameny.'},
 {id:'crest',name:'Korunoplaz',stage:2,role:'predator',shape:'crab',color:0x9bb7c0,size:1.3,speed:4.0,diet:['meat'],description:'Loví žrouty. Před výpadem ztuhne. Ostny a symbiotický štít zmírní zásah.'},
];
export const speciesById = (id:string) => SPECIES.find(s => s.id === id)!;
export const stageSpecies = (stage:Stage) => SPECIES.filter(s => s.stage === stage);
export const FOOD_LABEL: Record<string,string> = {algae:'Světelná řasa',mineral:'Křemenná výživa',nectar:'Nektarový kalich',meat:'Živočišná tkáň',detritus:'Úrodný detrit'};
export const TEXT = {
 firstLife:'První život ve světelné kapce',
 welcome:'Vítej v kapce. WASD: pohyb · mezerník: potrava · Tab: evoluce v kolébce.',
 occupiedSymbiote:'Partnerské lůžko nelze odstranit, dokud v něm žijí partneři.',
 reproduction:'Reprodukce a nová stavba těla',
 generationBorn:(generation:number)=>`Generace ${generation}. Nové tělo, stejná paměť.`,
 requirementNutrition:'Výživa linie',
 requirementExploration:'Prozkoumané niky',
 requirementNicheLife:'Život v každé nice',
 requirementGenerations:'Nové generace',
 requirementLungs:'Plíce pro vzduch',
 requirementLegs:'Končetiny pro oporu',
 requirementCount:(current:number,target:number)=>`${current} / ${target}`,
 developed:'vyvinuty',
 missing:'chybí',
 approachGate:'Dojdi k proudu na severu. Cestu ukazuje kompas.',
 transitionNotReady:'Linie ještě není připravena. Podmínky vidíš v deníku cesty.',
 finaleRestoration:'Tři prameny znovu žijí',
 finalePredator:'Rovnováha potravního řetězce obnovena',
 finaleMigration:'Symbiotická linie našla nový domov',
 victory:'Život si našel cestu. Tvoje linie zůstane v paměti přílivu.',
 huntedSpecies:(name:string)=>`${name}: lov změnil místní populaci. +5 DNA`,
 attackEnergy:'K útoku potřebuješ 2 energie. Nakrm se z nalezených zbytků.',
 firstMeal:'První potrava! Získej DNA, vrať se do kolébky a stiskni Tab.',
 depletedSource:'Zdroj vyčerpán. Místní půda si pamatuje odběr; zkus jinou niku nebo vrať živiny klávesou T.',
 symbiosisFull:'Obě symbiotické komůrky jsou obsazené. Krmení hostitele živí i partnery.',
 partnerJoined:(name:string)=>`${name} se připojil. Krm partnera: sdílí energii, prostor i osud.`,
 springRestored:(name:string,charge:number)=>`${name}: ${charge} / 10 · vracíš vodu do krajiny.`,
 soilRestored:'Živiny vráceny. Vegetace i potrava v nice se obnovují.',
 predatorHit:(stage:Stage)=>`Zásah predátora. ${stage===0?'Skryj se za kámen':stage===1?'Unikni mezi korály':'Skryj se za kmen'}, uhni stranou nebo použij obranu.`,
 droughtPeak:'Moře ustoupilo. Prázdné prameny vyschly; obnovené zdroje drží vláhu i život.',
 patchDiscovered:(name:string)=>`${name} · objevena nová nika. +8 DNA`,
 toxinPulse:'Obranný oblak. Toxiny stojí 15 energie.',
 sonarPulse:'Sonar mapuje zdroje a tvory v rozšířeném dosahu.',
 sonarEnergy:'Sonar potřebuje alespoň 3 energie.',
 deathEnergy:'Linie vyčerpala energii. Hledej potravu a omez sprint.',
 deathOxygen:'Došel kyslík. U hladiny se nadechni nebo vyviň žábry.',
 deathMoisture:'Tělo vyschlo. Prameny a zásobník vody pomáhají přežít.',
 deathPredator:'Predátor ukončil tuto generaci. Zkus úkryt, ostny nebo jinou niku.',
 nicheLearned:(name:string)=>`${name}: tvá linie zde našla způsob života. +5 DNA`,
 tooFarNest:'K nové generaci se vrať do kolébky. Sleduj značku ◇ na kompasu.',
 noFood:'V dosahu není vhodná potrava. Přibliž se ke zdroji nebo uprav ústní orgán.',
 incompatible:'Tato potrava neodpovídá tvým ústům. Změň specializaci v editoru.',
 needSymbiote:'K navázání vztahu potřebuješ symbiotickou komůrku.',
 noPartner:'Nablízku není kompatibilní partner. Hledej lucerničky, štítojemce nebo prachokřídlíky.',
 bondEnergy:'Partner potřebuje dar: alespoň 25 energie.',
 needLungs:'Na souš potřebuješ končetiny i plíce. Obojí je dostupné v editoru u kolébky.',
 death:'Tato generace dospěla ke konci.',
 restored:'Linie pokračuje z poslední uložené generace.',
 saved:'Paměť linie uložena.',
 noTend:'Přibliž se k prameni nebo zdroji a vrať živiny do půdy.',
 tendEnergy:'Obnova půdy stojí 10 energie. Nejdřív se nasyť.',
 bondLost:'Vyhladovělý partner opustil tělo. Symbióza vyžaduje péči.',
 drought:'Příliv ustupuje. Prameny slábnou. Vyber si cestu obnovy, rovnováhy nebo migrace.',
};
