/** Czech validation and persistence copy; schema rules stay in their modules. */
export const GENOME_ERRORS = {
  invalidStage: 'Neplatná evoluční etapa.',
  objectRequired: 'Genom musí být objekt.',
  invalidFields: 'Genom obsahuje chybějící nebo neznámá pole.',
  unsupportedVersion: 'Nepodporovaná verze genomu.',
  invalidName: 'Jméno musí mít 1 až 32 viditelných znaků.',
  invalidLength: 'Délka těla musí být 0,65 až 2,4.',
  invalidWidth: 'Šířka těla musí být 0,55 až 1,8.',
  invalidHue: 'Odstín musí být 0 až 360.',
  invalidPattern: 'Neplatný vzor těla.',
  invalidParts: 'Seznam částí těla není platný.',
  partLimit: 'Tělo může mít nejvýše 18 částí.',
  invalidPartId: 'Neplatný identifikátor části.',
  duplicatePartIds: 'Identifikátory částí se nesmějí opakovat.',
  unknownPartKind: 'Neznámý typ adaptace.',
  invalidAxial: 'Umístění části musí být mezi −1 a 1.',
  invalidAngle: 'Úhel části je mimo povrch těla.',
  invalidScale: 'Velikost části musí být 0,55 až 1,65.',
  invalidSymmetry: 'Symetrie části musí být zapnutá nebo vypnutá.',
  incompatibleMouths: 'Filtrační věnec a srpková čelist se vzájemně vylučují.',
  legsRequired: 'Na souši jsou nutné končetiny.',
  lungsRequired: 'Na souši jsou nutné vzdušné komory.',
  invalidOriginal: 'Původní genom není platný pro tuto etapu.',
  invalidBudget: 'Rozpočet DNA musí být nezáporné konečné číslo.',
  unknownAdaptation: (id:string) => `Neznámá adaptace: ${id}`,
  partObjectRequired: (position:number) => `Část ${position} není platný objekt.`,
  invalidPartFields: (position:number) => `Část ${position} obsahuje chybějící nebo neznámá pole.`,
  stageRequired: (name:string,stage:number) => `${name}: vyžaduje etapu ${stage}.`,
  attachmentLimit: (name:string,maximum:number) => `${name}: nejvýše ${maximum} úchytů.`,
  missingDna: (amount:number) => `Chybí ${amount} DNA.`,
};

export const SAVE_ERRORS = {
  objectRequired: 'očekáván objekt.',
  invalidFields: 'chybějící nebo neznámá pole.',
  invalidNumber: 'neplatná číselná hodnota.',
  invalidText: 'neplatný text.',
  booleanRequired: 'očekávána logická hodnota.',
  unknownValue: 'neznámá hodnota.',
  invalidCount: 'neplatný počet záznamů.',
  duplicateIds: 'opakující se identifikátory.',
  invalidLineageId: 'neplatný identifikátor linie.',
  worldMismatch: 'etapa nebo seed neodpovídá linii.',
  patchIds: 'niky musejí mít souvislé identifikátory 0, 1, 2.',
  unknownSpecies: 'neznámý druh pro tuto etapu.',
  missingLandmark: 'chybí kolébka, přechod nebo povinný pramen.',
  nextIdCollision: 'čítač může znovu vytvořit existující objekt.',
  unsupportedStateVersion: 'nepodporovaná verze herního stavu.',
  missingActiveWorld: 'chybí aktivní svět.',
  activeWorldMismatch: 'aktivní svět se rozchází s historií světů.',
  symbioteRequired: 'partner potřebuje partnerské lůžko.',
  invalidPartner: 'neplatný symbiotický partner.',
  partnerBenefitMismatch: 'schopnost neodpovídá partnerovi.',
  invalidNiche: 'neplatná nika.',
  duplicateDiscoveries: 'duplicitní objevy.',
  invalidFinale: 'neslučitelný stav dokončení kampaně.',
  unknownLineageAdaptation: 'neznámá adaptace v historii.',
  nestedCheckpoint: 'obnova nesmí obsahovat další zanořenou obnovu.',
  invalidCheckpointJson: 'neplatný JSON poslední generace.',
  checkpointMismatch: 'obnova nepatří této linii nebo pochází z budoucnosti.',
  tooLarge: 'Uložená hra přesahuje limit 8 MB.',
  invalidJson: 'Soubor není platná uložená hra: poškozený JSON.',
  envelopePath: 'soubor',
  invalidFormat: 'Soubor není uložená hra LUMAVORA.',
  unsupportedVersion: 'Tato verze uložené hry není podporována.',
  unserializableState: 'Herní stav nelze uložit: obsahuje neplatná nebo kruhová data.',
  cannotSave: 'Herní stav nelze uložit.',
  writeFailed: 'Prohlížeč nemohl uložit hru. Úložiště je plné nebo nepřístupné. Exportuj linii do souboru.',
  readFailed: 'Úložiště prohlížeče je nepřístupné. Zkus importovat exportovaný soubor.',
  notFound: 'Tato uložená linie nebyla nalezena.',
  slotIdMismatch: 'Identifikátor uložené linie nesouhlasí s jejím souborem.',
  deleteFailed: 'Uloženou linii nelze odstranit: úložiště je nepřístupné.',
  corrupted: (path:string,reason:string) => `Poškozená uložená hra (${path}): ${reason}`,
};
