export const MACHINE_COPY = {
  actualIncome:(rate:number)=>`Skutečný příjem: +${rate.toFixed(2)} jantaru/s.`,
  inheritedWork:(bonus:number)=>`Dědictví kmene: výkon při připojování +${Math.round(bonus*100)} %.`,
  regionalPower:'Výkon v regionu',
  basePower:'Základ konstrukce',
  catalog:'Díly stroje',designName:'Název konstrukce',length:'Délka trupu',width:'Šířka trupu',axial:'Poloha · záď ↔ příď',angle:'Poloha kolem trupu',partSize:'Velikost dílu',consequences:'Vlastnosti konstrukce',previewWork:'Práce modulu',drag:'Vyber díl na konstrukci a tažením změň jeho umístění',
  constructionNote:(remaining:number)=>`Zbude ${remaining.toFixed(0)} jantaru. Potvrzení vyrobí a zaplatí jeden nový stroj.`,
  title:'Ruce, které nepatří tělu',resource:'Jantar',income:'Příjem',fleet:'Flotila',regions:'Krajina',
  editor:'Konstrukce stroje',blueprint:'Návrh',build:'Vyrobit stroj',tank:'Pozemní nosič',air:'Létající nosič',
  durability:'Odolnost',power:'Výkon',speed:'Rychlost',mass:'Hmotnost',capacity:'Nosnost',currency:'jantar',
  locked:'Letouny se odemknou po připojení prvního regionu.',badBlueprint:'Konstrukce není platná.',
  shape:'Konstrukce obsahuje neznámá nebo chybějící pole.',name:'Pojmenuj konstrukci nejvýše 32 znaky.',
  dimensions:'Rozměry, barva nebo vzor jsou mimo povolený rozsah.',attachments:'Díly potřebují platné a jedinečné identifikátory a připojení k trupu.',
  hull:'Stroj potřebuje právě jeden trup.',cabin:'Stroj potřebuje právě jednu kabinu.',drive:'Nosič potřebuje právě jeden odpovídající pohon.',
  module:'Vyber právě jeden modul schopnosti.',carrier:'Tento díl nepatří na zvolený nosič.',overweight:'Konstrukce překračuje nosnost nosiče.',
  notEnough:'Na výrobu této konstrukce chybí jantar.',badBudget:'Zásoba jantaru není platná.',tooMany:'Flotila je plná. U dílny vyřaď vybraný stroj, aby vzniklo místo pro nový.',
  founded:'Kmen otevírá první dílnu. Navrhni pozemní stroj a zaber jantarový pramen.',
  objective:'Připoj tři regiony a nejméně dva jantarové prameny. První region odemkne letoun pro vysokou kotlinu.',
  select:'Vybrat flotilu',stop:'Zastavit',repair:'Opravit · 10 / stroj',home:'Dílna',capture:'Zabrat pramen',work:'Připojit region',next:'Obnovit celou planetu',
  help:'Klik a rámeček vybírají stroje, Shift přidává. Pravý klik na jantarový pramen zadá zábor, na region práci podle zděděné strategie. Tank získává prameny, letoun překoná srázy. WASD posouvá pohled, H míří domů, Tab otevře společný editor. Oprava a vyřazení vybraného stroje jsou dostupné u dílny. Vyřazení vrátí 35 % ceny a uvolní místo ve flotile. Po připojení prvního regionu otevři editor letounu.',
  none:'Vyber stroj nebo otevři editor a postav první konstrukci.',captured:'Připojený',neutral:'Nezávislý',
  delivery:'Zásobovací náklad',settlers:'Osady',relation:'Vztah',soil:'Obnova půdy',
  unavailable:'Stroje zatím nejsou v této etapě dostupné.',selectFirst:'Nejprve vyber živé stroje.',badTarget:'Tento cíl už není dostupný.',queueFull:'Fronta rozkazů je plná.',
  onlyTank:'Jantarový pramen může zabrat pouze pozemní stroj.',airRequired:'Vysoká kotlina leží za souvislým srázem. Potřebuje letoun.',wrongModule:'Tato konstrukce nemá modul pro zvolenou cestu.',
  built:'Stroj byl zaplacen a opustil dílnu.',springCaptured:'Jantarový pramen je připojen. Výroba dostává průběžný příjem.',
  retire:'Vyřadit · vrátit 35 % jantaru',retireHome:'S vyřazením se vrať do vzdálenosti 12 metrů od dílny.',lastMachine:'Poslední živý stroj flotily musí zůstat.',retired:'Stroj byl vyřazen. Část jantaru a nepoužité zásoby se vrátily do dílny.',
  repairHome:'S opravou se vrať ke kmenovému táboru.',repaired:'Stroje jsou opravené.',
  stranded:'Bez pozemního stroje a příjmu nelze získat další jantar. Můžeš obnovit poslední uložený začátek etapy.',recover:'Obnovit výchozí dílnu',
  ready:'Krajina drží společnou výrobu. Stroje jsou připravené na obnovu celé planety.',dead:'Flotila zanikla bez zdroje jantaru. Obnov výchozí dílnu.',
  regionJoined:(name:string)=>`${name}: region se připojil. Nosné rotory jsou dostupné v editoru.`,
  regionNames:{gardens:'Pramenné zahrady',terraces:'Jantarové terasy',highlands:'Vysoká kotlina'},
  strategy:{restoration:'Zahradníci obnovují půdu a dopravují zásoby pro osídlení.',predator:'Regulátoři musí prorazit obranu dělem.',migration:'Symbionti navazují obchod vysílačem a třemi zásobovanými návštěvami.'},
  parts:{
    hull:{name:'Jantarový trup',description:'Nese konstrukci a určuje její odolnost.',tradeoff:'Větší trup je pevnější, ale těžší.'},
    cabin:{name:'Kabina',description:'Posádka řídí stroj podle tvého rozkazu.',tradeoff:'Každý stroj má jednu kabinu.'},
    tracks:{name:'Pásový pohon',description:'Opora pro těžký stroj a zábor pramenů.',tradeoff:'Nepřekoná strmé srázy.'},
    rotor:{name:'Nosný rotor',description:'Udrží stroj nad terénem.',tradeoff:'Letoun neunese tak těžkou konstrukci.'},
    drill:{name:'Kořenový vrt',description:'Obnovuje půdu, usazuje osady a uvolňuje vodu.',tradeoff:'Těžký nástroj pro pozemní nosič.'},
    seeder:{name:'Rozsévač',description:'Rozptyluje život a vláhu z výšky.',tradeoff:'Potřebuje létající nosič; nezabírá prameny.'},
    cannon:{name:'Rázové dělo',description:'Prolomí ozbrojenou obranu regionu.',tradeoff:'Boj vyčerpá místní půdu a vyvolá odvetu.'},
    broadcast:{name:'Sborový vysílač',description:'Spojuje osady výměnou zásob a dohodou.',tradeoff:'Partnerství potřebuje opakované návštěvy.'},
    armor:{name:'Pancéřové štíty',description:'Zvyšují odolnost konstrukce.',tradeoff:'Přidají hmotnost a sníží rychlost.'},
  },
  categories:{structure:'Konstrukce',drive:'Pohon',module:'Schopnost',armor:'Ochrana'},
} as const;
