export const PROGRESSION_COPY = {
  passage: 'Připravenost k přechodu',
  ending: 'Živý domov',
  current: 'Současná podmínka',
  history: 'POZNÁNO · HISTORIE LINIE',
  missing: (labels: string[]) => `Ještě chybí: ${labels.join('; ')}. Podrobnosti ukazuje deník J.`,
  approach: (distance: number) => `Přibliž se k severnímu odtoku. Je ${distance.toFixed(1)} m daleko; G funguje do 10 m.`,
  ready: 'Cesta je připravena. G otevře další etapu.',
  legacyMigrationReady: 'Linie je připravena. G dovede partnery do nového domova.',
  noGate: 'V této krajině není další přechod.',
  automatic: 'Závěr na souši nastane automaticky, až domov přijme spory a získá živou oporu.',
  endingReady: 'Domov přijal spory a má živou oporu. Závěr se spustí automaticky.',
  sandbox: 'Tato linie už svůj závěr prožila. Nyní volně pokračuješ v jejím světě; další severní přechod není potřeba.',
  rootNeeded: 'Domov potřebuje živý porost u severního kořenového kruhu. Přines kulturu z jižního mateřského porostu.',
  supportNeeded: 'Spory dorazily. Udrž dvě živé opory krajiny, nebo podpoř domov založený spoluprací dvěma sytými, věrnými partnery a zásobníkem. Deník J ukazuje, co právě chybí.',
  alternatives: 'Domov potřebuje jednu z těchto dvou cest podpory:',
  network: 'Dvě živé opory krajiny',
  networkValue: (count: number) => `${count} / 2 právě žijí`,
  symbiosis: 'Symbiotická linie',
  symbiosisValue: (count: number, reservoir: boolean, guided: boolean) => `${count} / 2 partnerů s hladem pod 70 a věrností alespoň 35 · zásobník ${reservoir ? 'ano' : 'chybí'} · domov ze spolupráce ${guided ? 'ano' : 'chybí'}`,
  nextSite: (title: string) => `Tato změna je zapsaná. Další vztah čeká v nice: ${title}.`,
  nextPassage: 'Vztahy této etapy jsou poznané. Deník J ukazuje připravenost těla a severního přechodu.',
};
