import type { LegacyAbility, ToolId } from './era-types';

export const TRIBE_COPY = {
  dispositions: { friendly: 'Přátelští', neutral: 'Neutrální', hostile: 'Nepřátelští' },
  title: 'Kruh kolem ohně', subtitle: 'Jedno tělo dalo vzniknout celé tlupě.',
  enter: 'Založit kmen', enterHelp: 'Veď potomky své linie a původní symbionty. Jídlo živí tlupu i staví její domov; se sousedy se můžeš spojit, nebo je porazit.',
  founded: 'Kolem první chýše se schází tvoje linie. Vyber členy a pošli je pro potravu.',
  food: 'Jídlo', members: 'Členové', selected: 'Vybraní', equip: 'Výstroj', recruit: 'Přivolat potomka',
  selectAll: 'Vybrat tlupu', none: 'Bez nástroje', neighboursTitle: 'Za hranicí ohně',
  placeBuilding: 'Klikni na volné místo do 24 m od tábora. Esc umístění zruší.',
  chooseCommand: 'Vyber člena nebo přetáhni rámeček. Pravým klikem zadáš rozkaz.',
  gatherHelp: 'Potrava → pravý klik. Plný náklad člen odnese do chýše.',
  costFood: (cost: number) => `${cost} jídla`, capacity: (count: number, capacity: number) => `${count} / ${capacity}`,
  shelter: 'Chýše', workshop: 'Dílna', build: 'Postavit', gather: 'Sbírat', move: 'Přesun',
  attack: 'Zaútočit', socialize: 'Spřátelit', stop: 'Zastavit', home: 'Tábor',
  ability: 'Dědictví linie', next: 'Vstoupit do éry strojů', ready: 'Všichni sousedé patří do společného kruhu. Kmen je připraven stavět stroje.',
  objective: 'Spoj se se všemi třemi sousedy, nebo je poraz. Zachovej alespoň jednoho člena.',
  help: 'Levý klik nebo rámeček vybírá členy. Shift přidává výběr či rozkaz do fronty. Pravý klik na cizího člena útočí, Alt + pravý klik nabízí smír. Ústup domů vrátí vybrané členy. Pravý klik posílá jednotky, pravý tah otáčí pohled. WASD posouvá kameru; kolečko přibližuje. H vrátí pohled k táboru, Tab otevře výstroj, T použije dědictví, G pokračuje po sjednocení sousedů.',
  selectFirst: 'Nejprve vyber živé členy tlupy.', unavailable: 'Tato akce není v aktuální etapě dostupná.',
  notFood: 'Vybraní členové tento druh potravy nejedí. Rozhoduje zděděné tělo a druh symbionta.',
  noHunting: 'Tato linie neumí získávat potravu lovem. Ozbrojený konflikt se sousedy zůstává možný.',
  noFood: 'V táboře chybí jídlo. Pošli sběrače a počkej na jejich návrat s nákladem.',
  noRoom: 'Chýše jsou plné. Dokonči další chýši, nejvýše může žít dvanáct členů.',
  noWorkshop: 'Nejprve postav a dokonči dílnu tohoto nástroje.',
  badTarget: 'Tento cíl už není dostupný.', badPosition: 'Tady není volné místo pro stavbu.',
  tooManyBuildings: 'V této osadě už není místo pro další stavby.', queueFull: 'Fronta rozkazů je plná.',
  bodyLocked: 'Tělo kmene je zděděné. Změň výstroj jednotlivých členů.',
  cooldown: 'Dědictví se ještě obnovuje.', notReady: 'Nejprve vyřeš všechny sousední kmeny a zachovej živou tlupu.',
  dead: 'Zanikl poslední člen kmene. Obnov poslední bezpečný tábor.',
  built: 'Stavba je dokončená. Nové možnosti jsou dostupné v táboře.',
  equipped: 'Výstroj je zaplacená a členové ji nesou.', recruited: 'Nový potomek dorazil k ohni.',
  founding: 'Staveniště čeká na členy tlupy.', ordersGiven: 'Rozkaz přijat.',
  hungry: 'Hladový člen se vrací k zásobám.', noGift: 'Na setkání se sousedem chybí dar jídla.',
  allResolved: 'Kruh sousedů je uzavřen. Cesta ke strojům je otevřená.',
  alliance: (name: string) => `${name}: dar a společná píseň vytvořily spojenectví.`,
  conquest: (name: string) => `${name}: obrana ustoupila. Území se přidává k tvému kmeni.`,
  partner: 'Symbiont', lineage: 'Potomek', hunger: 'Hlad', health: 'Zdraví', cargo: 'Náklad',
  construction: 'Stavba', relation: 'Vztah', neutral: 'Nezávislí', allied: 'Spojenci', conquered: 'Připojení',
  tools: {
    basket: { name: 'Sběračský koš', hint: 'Unese pět porcí místo dvou. Nezmění jídelníček.' },
    spear: { name: 'Oštěp', hint: 'Delší dosah a silnější zásah. Lov potravy stále vyžaduje dravé tělo.' },
    drum: { name: 'Buben', hint: 'Společný rytmus mění dar jídla ve spojenectví.' },
    flute: { name: 'Píšťala', hint: 'Odpovídá na melodickou výzvu. Zabírá stejný slot jako pracovní nástroj.' },
    rattle: { name: 'Chřestidlo', hint: 'Odpovídá na šustivou výzvu. Zabírá stejný slot jako pracovní nástroj.' },
    waterskin: { name: 'Měch', hint: 'Péče o zraněné ve skupině a klidnější návštěva sousedů.' },
  } satisfies Record<ToolId, { name: string; hint: string }>,
  abilities: {
    restoration: { name: 'Paměť kořenů', hint: 'Obnoví potravu a půdu v okolí vybraného člena.' },
    predator: { name: 'Ochranný kruh', hint: 'Na chvíli zpevní obranu a ztiší odvetu sousedů.' },
    migration: { name: 'Společná cesta', hint: 'Nasytí a ošetří vybrané členy; blízké sousedy naladí k dohodě.' },
  } satisfies Record<LegacyAbility, { name: string; hint: string }>,
  neighbours: {
    garden: { name: 'Kmen pramenných sadů', hint: 'Přátelští sběrači nechávají zdroje u tvého domova tobě. Jídlem živí a obnovují vlastní osadu.' },
    terrace: { name: 'Strážci jantarové terasy', hint: 'Nepřátelští strážci při nedostatku vyšlou malou výpravu. Dar a osobní setkání ji uklidní.' },
    sanctuary: { name: 'Poutníci severního kruhu', hint: 'Největší společná hostina přináší nejpevnější přátelství.' },
  },
} as const;
