/** Czech interface copy. Replace this catalog for a second locale; view/DOM/event logic stays in main.ts.
 * Dynamic names supplied to HTML-facing formatters must already be escaped by the caller.
 * Adaptation and world catalogs remain in game/genome.ts and game/content.ts. */
export const COPY = {
  webglTitle: "Svět potřebuje WebGL 2",
  webglHelp: "Zapni grafickou akceleraci prohlížeče a obnov stránku.",
  all: "Vše",
  movement: "Pohyb",
  food: "Potrava",
  senses: "Smysly",
  defense: "Obrana",
  environment: "Prostředí",
  symbiosis: "Symbióza",
  brandSubtitle: "PAMĚŤ PŘÍLIVU",
  quality: "Kvalita obrazu",
  qualityLow: "Nízká",
  qualityMedium: "Střední",
  qualityHigh: "Vysoká · stíny",
  volumeMaster: "Celková hlasitost",
  volumeAmbience: "Zvuk prostředí",
  volumeEffects: "Zvuk interakcí",
  cameraSensitivity: "Citlivost kamery",
  mute: "Vypnout zvuk",
  reducedMotion: "Klidný obraz · méně pohybu",
  howToPlay: "Jak hrát",
  settings: "Nastavení",
  menuEyebrow: "Malý život. Velká stopa.",
  menuPromise: "Změň své tělo.<br>Změň příběh světa.",
  menuDescription: "Od první kapky k živé planetě. Vytvoř organismus, veď jeho kmen a sestav stroje, které pomohou světu dýchat samostatně.",
  newGame: "Zrodit novou linii <span>↗</span>",
  myLineages: "Moje linie",
  seedHeading: "SEMÍNKO SVĚTA",
  seedLabel: "Semínko světa",
  newSeed: "Nové semínko",
  organismFirst: "Organismus 001",
  heroTitle: "Všechno začíná<br>jediným nádechem.",
  heroCaption: "Jedno tělo. Tisíc možností.",
  menuGenre: "Originální evoluční odysea · 6 kapitol",
  localDevice: "Klávesnice + myš · ukládáno na tomto zařízení",
  importLineage: "IMPORT LINIE ↗",
  journalShortcut: "Deník cesty (J)",
  saveLineage: "Uložit linii",
  pauseShortcut: "Pauza (Esc)",
  livingWorld: "ŽIVÝ SVĚT",
  nursery: "Kolébka linie",
  nurserySubtitle: "Zde začíná další generace",
  yourJourney: "Tvoje cesta",
  droughtObjective: "Až voda odejde",
  evolutionObjective: "Za hranici známého",
  journal: "Deník cesty",
  dnaHeading: "EVOLUČNÍ DNA",
  vitality: "VITALITA",
  energy: "ENERGIE",
  oxygen: "KYSLÍK",
  moisture: "VLÁHA",
  worldMap: "Mapa světa",
  mapLegend: "NIKY · ◇ KOLÉBKA · △ CESTA",
  bond: "Spojit",
  restore: "Obnovit",
  pulse: "Pulz",
  pulseRecharging: (seconds: number) => `Pulz za ${seconds.toFixed(1)} s`,
  pulseReady: (energy: number) => `Pulz připraven · ${energy} energie`,
  pulseNeedsEnergy: (energy: number) => `Pulz potřebuje ${energy} energie`,
  pulseNeedsOrgan: "Vyviň toxickou žlázu nebo sonar.",
  evolution: "Evoluce",
  passage: "Cesta",
  seekPartner: "∞ Hledej partnera a stiskni R.",
  anatomyHint: "◌ Každá změna těla má důsledky.",
  betweenWorlds: "Mezi světy",
  nicheHint: " · Zkus zde potravu, lov, partnerství nebo obnovu.",
  followNursery: "Následuj světlo kolébky",
  explored: "PROZKOUMÁNO",
  unexplored: "NEZNÁMÁ NIKA",
  openSpace: "VOLNÝ PROSTOR",
  restoreSprings: "Obnovit prameny",
  stopInvaders: "Zastavit žrouty",
  migratePartners: "Převést partnery",
  nextGeneration: "Vytvořit další generaci",
  continueEvolution: "Pokračovat v evoluci",
  guideToSafety: "Dovést linii do bezpečí",
  tendHint: "Vrátit živiny · 10 energie",
  bondHint: "Nabídnout partnerství · 25 energie",
  eatHint: "Nasytit se",
  modalBrand: "LUMAVORA · PAMĚŤ LINIE",
  close: "Zavřít",
  pauseTitle: "Čas na nádech.",
  resume: "Pokračovat <span>↗</span>",
  save: "Uložit",
  controls: "Ovládání",
  mainMenu: "Hlavní menu",
  helpTitle: "Každé tělo je volba.",
  helpIntro: "Ovládáš jednu linii života. Sbírej potravu a DNA, prozkoumávej niky a v kolébce vytvoř další generaci. Svět si pamatuje každý odběr i pomoc.",
  moveKeys: "W A S D / šipky",
  moveControl: "Pohyb vůči kameře",
  verticalControl: "Stoupání / klesání pod vodou",
  sprintControl: "Sprint · stojí energii",
  spaceKey: "Mezerník",
  foodControl: "Potrava nebo útok čelistí",
  bondControl: "Partnerství · vyžaduje partnerské lůžko",
  tendControl: "Obnova zdroje nebo pramene · 10 energie",
  pulseControl: "Toxický oblak nebo sonarový pulz",
  editorControl: "Editor v kolébce · nová generace za 6 DNA + změny",
  passageControl: "Přechod u severní cesty po splnění podmínek",
  panelsControl: "Deník / pauza / celá obrazovka",
  rightMouse: "Pravá myš",
  orbitControl: "Otáčení kamery; kolečko přibližuje",
  editorHelp: "V editoru vyber orgán na těle nebo v seznamu. Posouvej jej po těle tažením myší nebo přesnými posuvníky. Pravé tlačítko otáčí náhled. Změny lze vrátit před potvrzením.",
  understood: "Rozumím <span>↗</span>",
  savesTitle: "Tvoje živé příběhy.",
  savesIntro: "Každá linie má vlastní paměť. Export uchová svět, tělo i ekologický vliv.",
  continue: "Pokračovat",
  deleteLineage: "Smazat linii",
  noSaves: "Žádná uložená linie. Začni nový život nebo importuj soubor.",
  export: "Export linie ↓",
  importFile: "Import souboru ↑",
  journalTitle: "Svět si pamatuje.",
  fieldInstruction: "V každé nice se alespoň jednou úspěšně nakrm, ulov tvora, navaž partnerství nebo vrať živiny pomocí T. Samotný průchod nestačí; první zdejší způsob života přinese 5 DNA.",
  restorationTitle: "01 · Obnova",
  restorationInstruction: "Každý ze tří pramenů naplň na 10 pomocí T. Jedna obnova stojí 10 energie. S partnerem je dvojnásobná.",
  predatorTitle: "02 · Rovnováha",
  predatorInstruction: "Ulovi 12 žroutů pramenů, poznej všechny niky a udrž alespoň 60 energie. Běžní býložravci se nepočítají.",
  migrationTitle: "03 · Migrace",
  migrationInstruction: "Přiveď dva partnery do svatyně na severu. Každý musí přežít 120 s a mít věrnost 35+. Potřebuješ rosný zásobník, 70 energie a objevené niky.",
  livingLandscape: "Živá krajina",
  fieldDone: "✓ Linie zde našla způsob života",
  fieldPending: "○ Vyzkoušej zde potravu, lov, partnerství nebo obnovu",
  inhabitants: "Obyvatelé této etapy",
  ecologyExplanation: "Odběr vyčerpává zdroje a půdu. Úrodnost řídí obnovu potravy a počet potomků. Lov mění počty druhů; invazní žrouti poškozují prameny. Jde o čitelnou herní simulaci.",
  backToWorld: "Zpět do světa <span>↗</span>",
  editorTitle: "Tělo vypráví příběh.",
  undo: "Zpět",
  redo: "Znovu",
  cancelEdits: "Zrušit úpravy",
  editorOrbit: "PRAVÁ MYŠ · OTOČIT &nbsp; / &nbsp; KOLEČKO · PŘIBLÍŽIT",
  editorDrag: "KLIK NA TĚLO · VYBRAT ČLÁNEK &nbsp; / &nbsp; TAŽENÍ ORGÁNU · PŘEMÍSTIT",
  adaptations: "Adaptace",
  pairPrice: "Cena páru",
  organPrice: "Cena orgánu",
  yourOrganism: "Tvůj organismus",
  lineageName: "Jméno linie",
  bodyLength: "Délka těla",
  bodyWidth: "Šířka těla",
  axialPosition: "Poloha · ocas ↔ hlava",
  angularPosition: "Poloha kolem těla",
  organSize: "Velikost orgánu",
  symmetry: "Párová symetrie · cena ×1,6",
  removePart: "Odstranit část ×",
  bodyConsequences: "Důsledky těla",
  speed: "Rychlost",
  turning: "Obratnost",
  protection: "Ochrana",
  perception: "Vnímání",
  metabolism: "Metabolismus",
  cosmetic: "Kosmetika · bez bonusu",
  hue: "Odstín",
  pattern: "Vzor",
  pearls: "Perly",
  stripes: "Pruhy",
  spots: "Skvrny",
  veins: "Žilkování",
  generationPrice: "CENA NOVÉ GENERACE",
  cancel: "Zrušit",
  confirmGeneration: "Zrodit generaci <span>↗</span>",
  consumption: "Spotřeba",
  unchanged: "beze změny",
  deathTitle: "Život nekončí jedním tělem.",
  deathHelp: "Uložená generace i její svět zůstávají v bezpečí. Po návratu máš deset sekund ochrany.",
  recover: "Obnovit poslední generaci <span>↗</span>",
  victoryTitle: "Svět si zapamatuje tvé jméno.",
  restorationEnding: "Voda se vrátila ke kořenům. Tři prameny znovu září díky tvé péči.",
  predatorEnding: "Invazní hlad ustoupil. Tvá linie vrátila potravnímu řetězci rovnováhu.",
  migrationEnding: "Dva životy se staly součástí jednoho těla. Svatyně deště ukrývá nový začátek.",
  sandbox: "Pokračovat ve světě <span>↗</span>",
  newLineage: "Nová linie",
  victoryHelp: "Tvé uložené linie zůstávají zachovány. Nové semínko nabídne jinou krajinu.",
  saved: "Paměť linie uložena.",
  saveFailed: "Uložení se nezdařilo.",
  returnForEvolution: "K evoluci se vrať do kolébky uprostřed mapy.",
  confirmDelete: "Smazat tuto uloženou linii? Tuto akci nelze vrátit.",
  deleteFailed: "Uloženou linii nelze odstranit.",
  exportFailed: "Export linie se nezdařil.",
  importTooLarge: "Soubor je příliš velký (maximum 8 MB).",

  generation: (value: number) => `GEN. ${String(value).padStart(2, '0')}`,
  patchStatus: (fertility: number, discovered: boolean) => `ÚRODNOST ${Math.round(fertility * 100)}% · ${discovered ? 'PROZKOUMÁNO' : 'NEZNÁMÁ NIKA'}`,
  drought: (value: number) => `Vysychání ${Math.round(value * 100)} % · naplněné prameny drží vláhu.`,
  saveSummary: (chapter: string, generation: number, seed: number) => `${chapter} · gen. ${generation} · seed ${seed}`,
  unknownPatch: (number: number) => `Neznámá nika ${number}`,
  patchHistory: (fertility: number, harvested: number, hunted: number, restored: number) => `Úrodnost ${Math.round(fertility * 100)}% · odběry ${harvested} · uloveno ${hunted} · obnova ${restored}`,
  editorGeneration: (generation: number) => `DÍLNA ŽIVOTA · GENERACE ${generation}`,
  unlockStage: (stage: number) => `Etapa 0${stage}`,
  anatomySummary: (parts: number, mass: number, abilities: number) => `${parts} částí · ${mass.toFixed(1)} hmotnost · ${abilities} schopností`,
  mutationPrice: (cost: number) => `6 reprodukce + ${cost} změny · vrácení částí nevyplácí DNA`,
  lineageVictory: (escapedName: string) => `LINIE ${escapedName} · PŘÍLIV DOKONČEN`,
  generationCount: (generation: number) => `${generation} generací`,
  mealAndHuntCount: (meals: number, kills: number) => `${meals} jídel · ${kills} lovů`,
  simulationMinutes: (minutes: number) => `${minutes} min simulačního času`,
  lineageStep: (generation: number, chapter: string) => `Generace ${generation} · ${chapter}`,
} as const;
