import type { GameState } from '../game/types';
import { activeMachines, machineDesign, machineIncome, machineEconomyStranded, machineHome } from '../game/machines';
import { horizontalDistance } from '../game/random';
import { vehicleStats } from '../game/blueprint';
import { MACHINE_COPY as C } from '../game/machine-copy.cs';
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const button=(action:string,label:string,disabled=false)=>`<button class="secondary" data-action="${action}"${disabled?' disabled':''}>${label}</button>`;
export function machineHudMarkup(s:GameState,selected:readonly number[]):string {
 const m=activeMachines(s);if(!m)return '';const units=m.fleet.filter(u=>selected.includes(u.id)),first=units[0],g=first?machineDesign(m,first):null,stats=g?vehicleStats(g):null;
 return `<div class="tribe-status panel"><div><span class="eyebrow">${C.resource}</span><strong>${Math.floor(m.resource)}</strong></div><div><span class="eyebrow">${C.income}</span><strong>+${machineIncome(m).toFixed(1)}/s</strong></div>${button('machine-all',C.select)}${button('machine-home',C.home+' · H')}</div>
 <aside class="tribe-neighbours panel"><span class="eyebrow">${C.regions}</span><p class="tiny">${C.objective}</p>${m.regions.map(r=>`<section class="tribe-neighbour"><button class="tribe-focus" data-action="machine-focus:region:${r.id}">${C.regionNames[r.identity]}<span>↗</span></button><div class="tiny">${r.owner==='player'?C.captured:m.archetype==='restoration'?`${C.soil} ${Math.round(r.soil)}% · ${C.settlers} ${r.settlers}/2`:m.archetype==='predator'?`${C.durability} ${Math.ceil(r.health)}`:`${C.relation} ${Math.round(r.relation)}% · ${r.deliveries}/3`}</div>${r.owner==='neutral'?`<div class="row">${button(`machine-region:${r.id}`,C.work,!units.length)}</div>`:''}</section>`).join('')}${m.completed?button('machine-next',C.next+' · G'):''}</aside>
 <aside class="tribe-selection panel machine-selection" tabindex="-1" aria-label="${C.fleet}"><div class="row spread"><span class="eyebrow">${C.fleet} · ${m.fleet.length}/8</span>${button('machine-stop',C.stop,!units.length)}</div><h3>${g?esc(g.name):C.none}</h3>${first&&stats?`<div class="tribe-member-stats"><span>${C.durability} <b>${Math.ceil(first.health)}/${stats.durability}</b></span><span>${C.power} <b>${stats.power.toFixed(1)}</b></span></div><p class="tiny">${g!.carrier==='tank'?C.tank:C.air} · ${C.speed} ${stats.speed.toFixed(1)} m/s<br>${C.delivery}: ${first.cargo}</p>`:`<p class="tiny">${C.strategy[m.archetype]}</p>`}<div class="tribe-roster">${m.fleet.map(u=>`<button class="tribe-unit${selected.includes(u.id)?' selected':''}" data-action="machine-select:${u.id}" title="${esc(machineDesign(m,u).name)}" aria-pressed="${selected.includes(u.id)}">${machineDesign(m,u).carrier==='tank'?'▰':'✣'} ${u.id}<i style="width:${u.health/vehicleStats(machineDesign(m,u)).durability*100}%"></i></button>`).join('')}</div><div class="machine-springs">${m.springs.map((p,i)=>`<div class="row"><button class="tribe-focus" data-action="machine-focus:spring:${p.id}">◈ ${i+1} · ${p.rate.toFixed(1)}/s</button>${button(`machine-capture:${p.id}`,p.owner==='player'?C.captured:C.capture,p.owner==='player'||!units.length)}</div>`).join('')}</div></aside>
 <nav class="tribe-orders panel">${machineEconomyStranded(s)?`<p>${C.stranded} ${button('machine-recover',C.recover)}</p>`:''}<div class="tribe-building-options">${button('machine-editor:tank',C.editor+' · '+C.tank,m.fleet.length>=8)}${button('machine-editor:air',m.airUnlocked?C.editor+' · '+C.air:C.locked,!m.airUnlocked||m.fleet.length>=8)}${button('machine-repair',C.repair,!units.length)}${button('machine-retire',C.retire,units.length!==1||m.fleet.filter(u=>u.health>0).length<=1||!first||horizontalDistance(first.pos,machineHome(s))>12)}</div><div class="tribe-command-hint">${C.strategy[m.archetype]} <button data-action="help">?</button></div></nav><div id="toast" class="toast" hidden></div>`;
}
