import type { GameState } from '../game/types';
import { cityAt } from '../game/cities';
import { activeMachines, machineDesign } from '../game/machines';
import { deploymentQuote, landRoute, DEFENSE_COST } from '../game/military';
import { vehicleStats } from '../game/blueprint';
import { cityEscape } from './cities';
export function militaryMarkup(s:GameState):string {
  const w=s.military,c=cityAt(s);if(!w||!c||s.stage!==4)return '';
  const d=w.deployment,m=activeMachines(s)!,u=m.fleet.find(u=>u.id===d?.unitId),here=d?.cityId===c.id,def=c.defense;
  const button=(cmd:string,label:string,disabled=false)=>`<button class="secondary" data-action="military:${cmd}" ${disabled?'disabled':''}>${label}</button>`;
  return `<h3>Vojenská cesta</h3><p>${c.capture?'✓ Převzato po porážce a obsazení':def?`Stráž · zdraví ${def.health.toFixed(1)} / ${vehicleStats(def.blueprint).durability} · zaplaceno ${DEFENSE_COST} ◈ z rezervy státu`:'Obrana dosud nezaplacená; žádná stráž zdarma.'}</p>${here&&u?`<p><strong>Tvůj tank #${u.id} · ${cityEscape(machineDesign(m,u).name)}</strong><br>Zdraví <strong>${u.health.toFixed(1)} / ${vehicleStats(machineDesign(m,u)).durability}</strong> · dosah 12<br>${d.phase==='field'?`Rozkaz: ${d.order==='attack'?'útok':d.order==='occupy'?'obsazení':d.order==='retreat'?'ústup':'stát'} · obsazení ${d.hold.toFixed(1)} / 5 s`:`Přeprava ${d.phase==='outbound'?'sem':'domů'} · zbývá ${d.remaining.toFixed(1)} s`}<br>Trasa: ${d.route.join(' → ')}</p>${button('camera','Vybrat tank a zaměřit boj')}${button('attack','Útok na stráž',d.phase!=='field'||!def||def.health<=0||!!c.capture)}${button('occupy','Obsadit náměstí · držet 5 s',d.phase!=='field'||!def||def.health>0||!!c.capture)}${button('stop','Zastavit / přerušit',d.phase!=='field')}${button('retreat','Ústup a návrat tanku',d.phase!=='field')}`:d?'<p>Tank je nasazený v jiném městě. Jeho boj a přeprava zde stojí.</p>':c.owner.kind==='state'?`<p>Vyber zaplacený tank u domácí dílny. Přeprava ${((landRoute(s,c)?.length??1)-1)*5} s, příplatek 0 ◈.</p>${m.fleet.map(u=>{const reason=deploymentQuote(s,c,u.id);return `<div>${button('deploy,'+u.id,`Nasadit #${u.id} · ${cityEscape(machineDesign(m,u).name)}`,!!reason)}${reason?`<p class="tiny">${cityEscape(reason)}</p>`:''}</div>`;}).join('')||'<p>Vyrob nejprve tank s dělem doma.</p>'}`:''}<p class="tiny">Dělo: 2× výkon / 1,2 s, dosah 12 a volný výhled. Žlutý kruh: tvůj tank; červený: stráž. Zničení nevrací cenu. Odchod zmrazí boj; návrat neléčí. Pauza a globál stojí. Tank ovládáš rozkazy; WASD dál pohybuje tvorem.</p><p role="status">${cityEscape(w.notice)}</p>`;
}
