import type { GameState } from '../game/types';
import { activePlanet, atPlanetBase, biomeLife, planetSampleTargets, planetSupport, planetVehicle } from '../game/planet';
import { activeMachines, machineDesign, machineHome } from '../game/machines';
import { vehicleStats } from '../game/blueprint';
import { ECOLOGY_CATALOG, ecologyTaxon } from '../game/ecology-catalog';
import { horizontalDistance } from '../game/random';
import { PLANET_COPY as C } from '../game/planet-copy.cs';
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const button=(action:string,label:string,disabled=false)=>`<button class="secondary" data-action="${action}"${disabled?' disabled':''}>${label}</button>`;
const roleLabel={producer:C.producer,herbivore:C.herbivore,predator:C.predator,partner:C.partner};
function climateChart(s:GameState){const p=activePlanet(s)!;return `<svg class="planet-climate" viewBox="0 0 300 300" role="img" aria-label="Teplota a vláha: bod uvnitř tří kruhů značí T3"><path d="M25 150H275M150 25V275"/><circle cx="150" cy="150" r="112"/><circle cx="150" cy="150" r="72.8"/><circle cx="150" cy="150" r="33.6"/><text x="250" y="143">T1</text><text x="209" y="143">T2</text><text x="155" y="143">T3</text><circle class="planet-climate-point" cx="${150+p.temperature*112}" cy="${150-p.atmosphere*112}" r="6"/><text x="150" y="15" text-anchor="middle">VLHKO</text><text x="150" y="295" text-anchor="middle">SUCHO</text><text x="8" y="165">CHLAD</text><text x="252" y="165">TEPLO</text></svg>`;}
function atlas(s:GameState,focus:number){const p=activePlanet(s)!,u=planetVehicle(s)!,base=machineHome(s);return `<svg class="planet-atlas" viewBox="0 0 180 180" aria-label="Mapa pobřeží a planetárních lokalit"><rect x="3" y="3" width="174" height="174" rx="12"/>${p.biomes.map(b=>`<circle cx="${90+b.pos.x}" cy="${90+b.pos.z}" r="${focus===b.id?8:5}" class="${biomeLife(s,b).support?'alive':''}"/><text x="${100+b.pos.x}" y="${94+b.pos.z}">${b.level}</text>`).join('')}<text x="${85+base.x}" y="${90+base.z}">⌂</text><circle cx="${90+p.nursery.pos.x}" cy="${90+p.nursery.pos.z}" r="3"/><path class="planet-position" d="M0 -5L4 5L0 3L-4 5Z" transform="translate(${90+u.pos.x} ${90+u.pos.z}) rotate(${180-u.heading*180/Math.PI})"/></svg>`;}
export function planetHudMarkup(s:GameState,map:boolean,chosen:number):string {
 const p=activePlanet(s),m=activeMachines(s),u=planetVehicle(s);if(!p||!m||!u)return '';const g=machineDesign(m,u),stats=vehicleStats(g),support=planetSupport(s),base=atPlanetBase(s),b=p.biomes.find(b=>b.id===chosen)??p.biomes[0],life=biomeLife(s,b),contacts=s.journey.ecology?.contacts??[],known=ECOLOGY_CATALOG.filter(t=>contacts.some(c=>c.key===t.key));
 const nearest=planetSampleTargets(s).filter(t=>horizontalDistance(t.pos,u.pos)<=8&&!contacts.some(c=>c.key===t.key)).sort((a,b)=>horizontalDistance(a.pos,u.pos)-horizontalDistance(b.pos,u.pos));
 const nursery=`<h3>${C.nursery}</h3><p class="tiny">${Math.round(horizontalDistance(u.pos,p.nursery.pos))} m · kultury lze odebrat, tvory nakrmit skutečnou porcí.</p>${nearest.map(t=>button(`planet-sample:${t.target.kind}:${t.target.id}`,`${t.target.kind==='culture'?'Odebrat':'Nakrmit'} · ${esc(ecologyTaxon(t.key)!.name)}`)).join('')}<div class="planet-nursery-actions">${['bell','gnaw','crest'].map(id=>button(`planet-nursery:${id}`,`Školka · ${ecologyTaxon('species:'+id)!.name} · 8`,!base)).join('')}</div>`;
 const community=`<div class="planet-biome-tabs">${p.biomes.map(b=>`<button data-action="planet-biome:${b.id}" class="${chosen===b.id?'active':''}">${b.level} · ${C.names[b.level-1]}</button>`).join('')}${button('planet-biome:0','Školka')}</div>${chosen===0?nursery:`<h3>${C.names[b.level-1]}</h3><p class="tiny">${Math.round(horizontalDistance(u.pos,b.pos))} m · T${b.level} · ${life.support?C.stable:C.unstable}</p>${(['producer','herbivore','predator'] as const).map(role=>{const group=role==='producer'?life.roots:role==='herbivore'?life.herbs:life.predators,max=role==='predator'?1:2;return `<section class="planet-trophic"><span class="eyebrow">${roleLabel[role]} · ${group.length}/${max}</span>${group.map(c=>`<div class="planet-life-row"><span>${esc(ecologyTaxon(c.key)!.name)}<small>${'site'in c?Math.round(c.site.vitality)+'% kořeny':Math.round(c.vitality)+'% · '+c.abundance.toFixed(1)+' populace · potrava '+Math.round(c.nutrition*100)+'%'}</small></span><button data-action="planet-remove:${c.id}" title="Odstranit tuto populaci">×</button></div>`).join('')}${group.length<max?known.filter(t=>t.role===role&&!group.some(c=>c.key===t.key)).map(t=>button(`planet-introduce:${b.id}:${t.key}`,`${role==='producer'?'Zasadit':'Usídlit'} · ${esc(t.name)}`,p.tScore<b.level)).join(''):''}${!known.some(t=>t.role===role)?'<p class="tiny">Chybí kontakt. Navštiv školku nebo mateřský porost.</p>':''}</section>`;}).join('')}`}`;
 return `<div class="tribe-status panel planet-status"><div><span class="eyebrow">Planeta</span><strong>T${p.tScore}</strong></div><div><span class="eyebrow">Živá opora</span><strong>${support}/3</strong></div><div><span class="eyebrow">Jantar</span><strong>${Math.floor(m.resource)}</strong></div>${button('planet-map',map?C.landscape:C.map)}</div>
 <aside class="planet-vehicle panel"><span class="eyebrow">Přímé řízení · V přepne stroj</span><h3>${esc(g.name)}</h3><p class="tiny">${g.carrier==='air'?'Letoun':'Pozemní stroj'} · ${stats.speed.toFixed(1)} m/s · výkon ${stats.power.toFixed(1)}<br>${stats.module==='drill'?C.drill:stats.module==='seeder'?C.seeder:C.wrongTool}</p>${button('planet-tool',p.toolOn?C.toolOn:C.toolOff,!['drill','seeder'].includes(stats.module??''))}<div class="tribe-roster">${m.fleet.filter(v=>v.health>0).map(v=>`<button data-action="planet-vehicle:${v.id}" class="tribe-unit${u.id===v.id?' selected':''}" title="${esc(machineDesign(m,v).name)}">${machineDesign(m,v).carrier==='air'?'✣':'▰'} ${v.id}</button>`).join('')}</div>${atlas(s,chosen)}<div class="planet-base-actions">${button('planet-editor:tank','Vyrobit tank',!base||m.fleet.length>=8)}${button('planet-editor:air','Vyrobit letoun',!base||m.fleet.length>=8)}${button('planet-retire','Vyřadit · vrátit 35 % jantaru',!base||m.fleet.length<=1)}</div><p class="tiny">Dílna ⌂ · ${Math.round(horizontalDistance(u.pos,machineHome(s)))} m</p></aside>
 <aside class="planet-community panel">${community}</aside>
 ${map?`<section class="planet-map panel"><div><span class="eyebrow">${C.title}</span><h2>T${p.tScore} · ${p.tScore} ${p.tScore===1?'osada':'osady'}</h2>${climateChart(s)}<p class="tiny">Teplota ${p.temperature.toFixed(2)} · vláha ${p.atmosphere.toFixed(2)}<br>${p.toolOn?'Nástroj pracuje':'Nástroje vypnuté'} · samostatná stabilita ${Math.floor(p.stableTime)}/30 s</p></div><div><h3>Paměť živé linie</h3><p class="tiny">${C.objective}</p><div class="planet-catalog">${known.map(t=>{const c=contacts.find(c=>c.key===t.key)!;return `<p><b>${esc(t.name)}</b><small>${roleLabel[t.role]} · etapa ${c.stage+1} · ${{culture:'odebraná kultura',feeding:'skutečná hostina',hunt:'lov',bond:'symbióza'}[c.method]}</small></p>`;}).join('')}</div></div></section>`:''}
 <nav class="tribe-orders panel planet-orders"><div class="planet-controls"><span>WASD · řídit</span>${button('planet-map','M · '+(map?C.landscape:C.map))}${button('planet-tool','␣ · nástroj')}${button('planet-sample','T · živý kontakt')}${button('planet-biome:0','Školka')}${button('help','?')}</div></nav><div id="toast" class="toast" hidden></div>`;
}
