import { incomingMarkup } from './defense';
import type { GameState } from '../game/types';
import { STATE_PROFILES, STATE_TURN_LIMIT, stateCities, type StateAction } from '../game/states';
import { CITY_BUILDINGS } from '../game/city-economy';
import { cityEscape } from './cities';
export const stateActionText=(a:StateAction|null)=>!a?'Vyčkávání':a.kind==='found'?'Založení města':a.kind==='open'?'Otevření hospodářství':a.kind==='fund'?'Převod 20 do města':a.kind==='invite'?'Pozvání dvou občanů':a.kind==='defend'?'Nákup městské stráže':a.kind==='raid'?'Placený protiútok':`Stavba: ${CITY_BUILDINGS[a.building].name}`;
export function statesMarkup(s:GameState):string {
  const states=s.states;if(!states)return '';
  if(!states.activated)return '<h3>Soupeřící státy</h3><p>Nové státy se aktivují při místním hraní po dosažení strojové etapy. Minulá osídlení ani rozhodnutí se nedoplňují.</p>';
  return `${incomingMarkup(s)}<h3>Státy · strategický tah ${states.clock.turn}</h3><p class="tiny">${states.clock.turn>=STATE_TURN_LIMIT?'Dosažen limit strategického času.':`Další rozhodnutí za ${(10-states.clock.elapsed).toFixed(1)} s místního hraní.`} Pauza, editor, knihovna a globál stojí. Městská výroba běží jen při návštěvě.</p><details data-preserve-open><summary>Původ a pravidla rozpočtu</summary><p>${states.origin==='birth'?'Pravidla od narození linie':'Nově aktivované v historické kampani'} · aktivace v etapě ${states.activated.stage+1}, tick ${states.activated.tick}. Každý stát dostal jednou 400 jantaru jako počáteční rezervu. Další strategický příjem 0. Založení 60, převod do města 80. Nejvýše dvě města; osídlení zabírá jen volnou pevninu.</p><p>Zde jsou dostupné všechny zaznamenané informace o státech. Jejich minulost před aktivací není známá. Původní kmeny a stroje zůstávají samostatné.</p></details>${states.entries.map(r=>{
    const profile=STATE_PROFILES[r.profile],cities=stateCities(s,r),last=r.last;
    return `<article class="state-card" style="border-color:${profile.color}"><h4>${profile.name}</h4><p><strong>Rezerva ${r.reserve} / ${r.endowment} ◈</strong> · ${cities.length}/2 měst<br>Priorita: ${CITY_BUILDINGS[profile.priority].name}</p><p class="state-last">${last?`Tah ${last.turn} · ${last.outcome==='paid'?'Zaplaceno':'Neprovedeno'} · ${stateActionText(last.action)}<br>${cityEscape(last.reason)}`:'Dosud žádné rozhodnutí; první osídlení se vyhodnotí v prvním tahu.'}</p><ul>${cities.map(c=>`<li><button class="secondary" data-action="city-select:${cityEscape(c.id)}">${cityEscape(c.name)}</button> ${c.economy?`${c.economy.residents.length} občanů · pokladna ${c.economy.treasury} ◈`:'hospodářství neotevřené'}</li>`).join('')}</ul><details data-preserve-open><summary>Zaplacené doklady · ${r.transactions.length}</summary><ol>${r.transactions.map(t=>`<li>Tah ${t.turn}: ${stateActionText(t.action)} · ${t.cost} ◈ z ${t.account==='reserve'?'rezervy státu':'městské pokladny'}<br><small>${cityEscape(t.id)}</small></li>`).join('')}</ol></details></article>`;
  }).join('')}`;
}
