/** Preserve live controls, pointer targets and keyboard focus while counters change.
 * Only trusted markup generated by our UI modules is accepted. */
export function syncMarkup(root: HTMLElement, markup: string): void {
  const template = document.createElement('template');
  template.innerHTML = markup;
  function sync(parent: Node, desired: Node) {
    const next = [...desired.childNodes];
    for (let i = 0; i < next.length; i++) {
      const incoming = next[i], current = parent.childNodes[i];
      if (!current) { parent.appendChild(incoming.cloneNode(true)); continue; }
      if (current.nodeName !== incoming.nodeName) { parent.replaceChild(incoming.cloneNode(true), current); continue; }
      if (current instanceof Element && incoming instanceof Element) {
        for (const name of current.getAttributeNames()) if (!incoming.hasAttribute(name)) current.removeAttribute(name);
        for (const name of incoming.getAttributeNames()) if (current.getAttribute(name) !== incoming.getAttribute(name)) current.setAttribute(name, incoming.getAttribute(name)!);
        sync(current, incoming);
      } else if (current.nodeValue !== incoming.nodeValue) current.nodeValue = incoming.nodeValue;
    }
    while (parent.childNodes.length > next.length) parent.removeChild(parent.lastChild!);
  }
  sync(root, template.content);
}
