import type { GameState } from '../game/types';
import type { ToolId } from '../game/era-types';
import { activeTribe, memberDiet, tribeCapacity, TRIBE_COSTS, TRIBE_TOOLS } from '../game/tribe';
import { neighbourGift } from '../game/tribe-neighbours';
import { TRIBE_COPY as C } from '../game/tribe-copy.cs';
import { FOOD_LABEL, speciesById } from '../game/content';
import { COPY } from './copy.cs';

export type TribeBuildChoice = { kind: 'shelter' | 'workshop'; tool: ToolId | null };
const escape = (s: unknown) => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
const button = (action: string, label: string, disabled = false, selected = false) => `<button class="secondary${selected ? ' active' : ''}" data-action="${action}"${disabled ? ' disabled' : ''}>${label}</button>`;
const toolSymbol: Record<ToolId, string> = { basket: '▥', spear: '↟', drum: '◉', waterskin: '◒' };

export function tribeHudMarkup(s: GameState, selected: readonly number[], building: TribeBuildChoice | null): string {
  const t = activeTribe(s); if (!t) return '';
  const members = t.members.filter(u => selected.includes(u.id)), first = members[0];
  const resourceKinds = first ? memberDiet(s, first).map(k => FOOD_LABEL[k as keyof typeof FOOD_LABEL]).join(' · ') : '';
  return `<div class="tribe-status panel"><div><span class="eyebrow">${C.food}</span><strong>${Math.floor(t.food)}</strong></div><div><span class="eyebrow">${C.members}</span><strong>${C.capacity(t.members.length, tribeCapacity(t))}</strong></div>${button('tribe-all', C.selectAll)}${button('tribe-home', `${C.home} · H`)}</div>
  <aside class="tribe-neighbours panel"><span class="eyebrow">${C.neighboursTitle}</span><p class="tiny">${C.objective}</p>${t.neighbours.map(n => `<section class="tribe-neighbour"><button class="tribe-focus" data-action="tribe-focus:${n.id}">${C.neighbours[n.identity].name}<span>↗</span></button><div class="tiny">${n.resolved ? n.resolved === 'allied' ? C.allied : C.conquered : `${C.relation} ${Math.round(n.relation)} · ${C.costFood(neighbourGift(n))}`}</div><div class="meter"><i style="width:${n.resolved ? 100 : Math.max(0,n.relation)}%"></i></div>${!n.resolved ? `<div class="row">${button(`tribe-socialize:${n.id}`, C.socialize, !members.length)}${button(`tribe-attack:${n.id}`, C.attack, !members.length)}</div>` : ''}</section>`).join('')}${t.completed ? button('tribe-next', `${C.next} · G`) : ''}</aside>
  <aside class="tribe-selection panel" tabindex="-1" aria-label="${C.equip}"><div class="row spread"><span class="eyebrow">${C.selected} · ${members.length}</span>${button('tribe-stop',C.stop,!members.length)}</div><h3>${first ? escape(first.species ? speciesById(first.species).name : s.player.genome.name) : C.chooseCommand}</h3>${first ? `<p class="tiny">${resourceKinds}</p><div class="tribe-member-stats"><span>${C.health} <b>${Math.round(first.health)}</b></span><span>${C.hunger} <b>${Math.round(first.hunger)}</b></span><span>${C.cargo} <b>${first.cargo}</b></span></div><div class="tribe-tools">${TRIBE_TOOLS.map(tool => `<button data-action="tribe-equip:${tool}" class="secondary${first.tool===tool?' active':''}" title="${escape(C.tools[tool].hint)}"${!t.unlocked.includes(tool)?' disabled':''}>${toolSymbol[tool]} ${C.tools[tool].name}<small>${C.costFood(TRIBE_COSTS.equip)}</small></button>`).join('')}${button('tribe-equip:none',C.none)}</div>` : `<p class="tiny">${C.gatherHelp}</p>`}<div class="tribe-roster">${t.members.map(u => `<button class="tribe-unit${selected.includes(u.id)?' selected':''}" data-action="tribe-select:${u.id}" title="${escape(u.species ? speciesById(u.species).name : C.lineage)} · ${C.hunger} ${Math.round(u.hunger)}" aria-pressed="${selected.includes(u.id)}"><span>${u.species?'∞':'◌'} ${u.id}</span><small>${u.tool?toolSymbol[u.tool]:'—'}</small><i style="width:${u.health}%"></i></button>`).join('')}</div></aside>
  <nav class="tribe-orders panel"><div class="tribe-building-options">${button('tribe-recruit',`${C.recruit}<small>${C.costFood(TRIBE_COSTS.recruit)}</small>`,t.food<TRIBE_COSTS.recruit||t.members.length>=tribeCapacity(t))}${button('tribe-build:shelter',`${C.shelter}<small>${C.costFood(TRIBE_COSTS.shelter)}</small>`,!members.length||t.food<TRIBE_COSTS.shelter,building?.kind==='shelter')}${TRIBE_TOOLS.map(tool=>button(`tribe-build:${tool}`,`${C.workshop} · ${toolSymbol[tool]}<small>${C.tools[tool].name} · ${TRIBE_COSTS.workshop}</small>`,!members.length||t.food<TRIBE_COSTS.workshop,building?.tool===tool)).join('')}${button('tribe-ability',`${C.abilities[t.legacyAbility].name}<small>T · ${t.abilityCooldown>0?Math.ceil(t.abilityCooldown)+' s':C.costFood(TRIBE_COSTS.ability)}</small>`,!members.length||t.abilityCooldown>0||t.food<TRIBE_COSTS.ability)}</div><div class="tribe-command-hint">${building?C.placeBuilding:C.gatherHelp} <button data-action="help">${COPY.controls}</button></div></nav>
  <div id="toast" class="toast" hidden></div>`;
}
