import type { GameState } from '../game/types';
import { worldSpecies } from '../game/npc-genome';
import { horizontalDistance } from '../game/random';
import { ANIMAL_REASONS, animalCapacity, animalMaxHealth, animalResources, animalStatus, domesticationQuote } from '../game/tribe-domestication';
import { FOOD_LABEL } from '../game/content';
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const button=(action:string,label:string,disabled=false)=>`<button class="secondary" data-action="tribe-${action}"${disabled?' disabled':''}>${label}</button>`;
export const ANIMAL_STATUS={lost:'Zvíře se ztratilo',afraid:'Vyplašený · vrací se',hungry:'Hladový · práce stojí',unattended:'Chybí klidný pečující',carrying:'Nese skutečné porce',gathering:'Sbírá',resting:'Odpočívá doma'} as const;
export function domesticationMarkup(s:GameState,ids:readonly number[]):string{
 const t=s.tribe?.version===2?s.tribe:null;if(!t)return '';
 const d=t.domestication,e=d?.active,own=t.members.filter(u=>u.health>0&&!u.species),animals=d?.animals??[],home=t.huts.find(h=>h.kind==='shelter'&&h.progress===1)!.pos;
 return `<aside class="domestication panel" aria-label="Domestikace"><div class="row spread"><span class="eyebrow">Zvířata · ${animals.length+(e?1:0)} / ${animalCapacity(t)}</span>${button('animals-close','Zavřít')}</div>
 <h3>Zvonkonoši kmene</h3><p class="tiny">Domácí sběrač je skutečné divoké zvíře, které jsi získal. Není potomkem tvého druhu ani symbiontem; během péče není lovnou kořistí.</p>
 <div class="animal-caretakers"><span class="tiny">Vyber pečujícího:</span>${own.map(u=>`<button class="secondary${ids.length===1&&ids[0]===u.id?' active':''}" data-action="tribe-select:${u.id}">◌ ${u.id}</button>`).join('')}</div>
 ${e?`<section class="animal-acquisition"><div class="animal-heading">#${e.creature} · ${e.phase==='approach'?'Přiblížení':e.phase==='lure'?'Uklidnění v kontaktu':'Doprovod domů'}</div><p class="tiny">Pečující ${e.caretaker} · zaplaceno ${e.paid} / 6 jídla<br>Zbývá ${Math.ceil(e.remaining)} s · klid ${e.progress.toFixed(1)} / 8 s${e.contactLost>0?`<br>Kontakt chybí ${e.contactLost.toFixed(1)} / 4 s`:''}</p><div class="meter"><i style="width:${e.progress/8*100}%"></i></div><p class="tiny">Pečující čeká na zvíře a vede je domů. Nový rozkaz nebo útok pokus ukončí. Po zaplacení bez vratky.</p><div class="row">${button(`animal-focus:${e.creature}`,'Ukázat zvíře')}${button('tame-cancel','Přerušit')}</div></section>`:''}
 ${d?.result?`<p class="animal-result" role="status">#${d.result.creature}: ${ANIMAL_REASONS[d.result.reason]}${d.result.paid?` Zaplaceno ${d.result.paid} jídla.`:''}</p>`:''}
 ${animals.map(a=>{const c=s.world.creatures.find(c=>c.id===a.creature),u=t.members.find(u=>u.id===a.caretaker),status=animalStatus(s,a);return `<section class="animal-card"><div class="row spread"><strong>Domácí #${a.creature}</strong>${button(`animal-focus:${a.creature}`,'Ukázat ↗')}</div><p class="animal-heading">${ANIMAL_STATUS[status]}</p><p class="tiny">Zdraví ${Math.round(c?.health??0)} / ${c?animalMaxHealth(s,c):0} · hlad ${Math.round(c?.hunger??0)} / 100<br>Důvěra ${Math.round(a.trust)} / 100 · náklad ${a.cargo} / 6<br>Pečující ${a.caretaker??'chybí'}${u?` · ${Math.round(horizontalDistance(u.pos,home))} m od domova`:''}${a.resource!==null?`<br>Cíl: zdroj #${a.resource}`:''}</p><div class="row">${button(`animal-care:${a.creature}`,'Přidělit vybraného')}${button(`animal-rest:${a.creature}`,'Domů')}</div><details data-preserve-open><summary>Sběr řasy / nektaru do 32 m</summary><p class="tiny">6 porcí × 4 = 24 jídla až po doručení. Každé sousto ubývá skutečnému zdroji.</p>${animalResources(s).sort((a,b)=>horizontalDistance(a.pos,home)-horizontalDistance(b.pos,home)||a.id-b.id).slice(0,8).map(r=>button(`animal-gather:${a.creature}:${r.id}`,`${FOOD_LABEL[r.kind]} #${r.id} · ${Math.floor(r.amount)} porcí`)).join('')||'<p class="tiny">V okolí není vhodný zdroj s celou porcí.</p>'}</details><div class="row">${button(`animal-release:${a.creature}`,'Uvolnit do divočiny')}</div></section>`;}).join('')}
 <details class="animal-rules" data-preserve-open><summary>Péče, cena a omezení</summary><p class="tiny">Dva na dokončený přístřešek, nejvýše tři. Získání: 6 jídla při kontaktu, 8 s klidu, poté fyzická cesta domů; celkem do 90 s.</p><p class="tiny">Doma pečující bez oštěpu a s hladem pod 70 krmí v kontaktu: 3 jídla ze skladu při hladu zvířete ≥30, sníží jej o 32. Sklad představuje zpracované kmenové zásoby; jídelníček tvého těla se nemění. Jeden člen může pečovat o více zvířat.</p><p class="tiny">Hlad roste o 0,65/s. Od 70 sběr i výnos stojí, od 90 ubývá zdraví. Hlad nebo ztráta člena snižuje důvěru; při nule zvíře odejde a náklad se ztratí. Sytá péče obnovuje důvěru i zdraví. Po útoku se vrací domů; po uklidnění zadej sběr znovu. Uvolnění nic nevrací. Smrt ponechá jednu běžnou mršinu. V další etapě se péče zmrazí bez nového bonusu.</p></details>
 ${!e?`<details class="animal-wild" data-preserve-open${animals.length?'':' open'}><summary>Najít divoké zvíře</summary><p class="tiny">Zvonkonoš sbírá rostliny. Prachokřídlík zůstává symbiontem, korunoplaz lovcem a žrout invazní faunou.</p>${s.world.creatures.filter(c=>c.health>0&&!animals.some(a=>a.creature===c.id)).sort((a,b)=>(a.species==='bell'?-1:1)-(b.species==='bell'?-1:1)||horizontalDistance(a.pos,home)-horizontalDistance(b.pos,home)||a.id-b.id).slice(0,8).map(c=>{const quote=domesticationQuote(s,ids,c.id);return `<section class="animal-candidate"><div class="row spread"><strong>${esc(worldSpecies(s.world,c.species).name)} #${c.id}</strong>${button(`animal-focus:${c.id}`,'Ukázat ↗')}</div><p class="tiny">${Math.round(horizontalDistance(c.pos,home))} m od domova · zdraví ${Math.round(c.health)} / ${animalMaxHealth(s,c)}<br>${esc(quote.message)}</p>${c.species==='bell'?button(`tame:${c.id}`,'Získat · 6 jídla',!quote.ok):''}</section>`;}).join('')||'<p class="tiny">Žádné živé zvíře. Domestikace zvířata nevytváří.</p>'}</details>`:''}</aside>`;
}
