/** B2 native continuation of the real J export. No live-state writes/test clock. */
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {chromium} from 'playwright';
const base=process.env.LUMAVORA_URL??'http://127.0.0.1:5220',out=path.resolve(process.env.CIVILIZATION_OUTPUT??'evidence/sp-007b2/browser');await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'}),context=await browser.newContext({viewport:{width:1280,height:720},acceptDownloads:true});
if(process.env.LUMAVORA_TRACE==='1')await context.tracing.start({screenshots:true,snapshots:true,sources:true});
const page=await context.newPage(),checks=[],errors=[];let frames=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('dialog',d=>d.accept());
const read=()=>page.evaluate(()=>JSON.parse(window.render_game_to_text()));
const act=async a=>page.locator(`[data-action="${a}"]:visible`).first().click();
const check=n=>{checks.push(n);console.log(n);};
const shot=async n=>{await page.waitForTimeout(200);await page.screenshot({path:path.join(out,n+'.png')});};
const pause=async()=>{if((await read()).mode==='game')await act('pause');};
const imported=async(file)=>{await page.goto(base);await act('saves');await page.locator('#import-save').setInputFiles(path.resolve(file));await page.waitForFunction(()=>JSON.parse(window.render_game_to_text()).mode==='game');assert.equal(await page.evaluate(()=>typeof window.advanceTime),'undefined');};
const exported=async name=>{await pause();if((await read()).mode!=='saves')await act('saves');const pending=page.waitForEvent('download');await act('export');const dl=await pending,file=path.join(out,name+'.save.json');await dl.saveAs(file);return file;};
try{
 await imported('evidence/sp-009j/browser/paid-carriers.save.json');if((await read()).navigation.field)await act('travel-home');assert.equal((await read()).civilization.entry,'required');
 assert.ok(await page.locator('[data-action="machine-next"]').isDisabled());await page.keyboard.press('g');assert.equal((await read()).stage,4);assert.equal((await read()).civilization.completed,null);
 await page.setViewportSize({width:1024,height:640});await shot('blocked-unification-1024');check('Completed home regions cannot bypass four real rival cities; both native button and G refuse passage');
 await imported('tests/fixtures/commerce/native-trade-campaign.save.json');if((await read()).navigation.field)await act('travel-home');const before=await read(),old=structuredClone(before.lineageHistory.stages[4]);assert.ok(!await page.locator('[data-action="machine-next"]').isDisabled());
 await page.setViewportSize({width:1280,height:720});await shot('ready-unification-1280');
 await act('machine-next');await page.waitForFunction(()=>JSON.parse(window.render_game_to_text()).stage===5);let s=await read();assert.equal(s.civilization.completed.cities.length,5);assert.deepEqual(s.lineageHistory.stages[4],old);const complete=structuredClone(s.civilization.completed);
 check('Actual J cities and funded productive city unlock 4→5; completion records five exact city prefixes and leaves frozen regional history unchanged');
 await act('journal');assert.match(await page.locator('.civilization-history').innerText(),/obchodní/);assert.match(await page.locator('.civilization-history').innerText(),/20 %/);await page.locator('.civilization-history').scrollIntoViewIfNeeded();await shot('civilization-journal-1280');await act('close');
 s=await read();const tank=s.machines.fleet.find(u=>s.machines.blueprints.find(b=>b.id===u.blueprint).blueprint.name==='Měděný posel');await act('planet-vehicle:'+tank.id);await act('planet-tool');const working=await read();assert.equal(working.planet.toolOn,true);frames=await page.evaluate(()=>new Promise(resolve=>{const a=[];let last;function sample(t){if(last!==undefined)a.push(t-last);last=t;if(a.length===90)resolve(a);else requestAnimationFrame(sample);}requestAnimationFrame(sample);}));await pause();const after=await read(),seconds=after.planet.elapsed-working.planet.elapsed,income=after.machines.springs.filter(p=>p.owner==='player').reduce((n,p)=>n+p.rate,0),observed=after.machines.resource-working.machines.resource;
 assert.ok(Math.abs(observed-(income-.20)*seconds)<1e-6);check(`Actual tool consumption0.20/s confirmed over ${seconds.toFixed(3)} native simulation seconds; spring income measured separately`);
 await act('close');await act('planet-tool');await page.setViewportSize({width:1024,height:640});await page.locator('[data-civilization-effect]').scrollIntoViewIfNeeded();await shot('inherited-tool-1024');
 const saved=await exported('active-campaign');await imported(saved);await pause();await act('save');await page.reload();await act('saves');await page.locator('[data-action^="load:"]').first().click();await pause();s=await read();assert.equal(s.stage,5);assert.deepEqual(s.civilization.completed,complete);assert.deepEqual(s.lineageHistory.stages[4],old);check('Export/import/rekey and save/reload/load preserve exact completion and downstream state');
 await imported('tests/fixtures/saves/stable-sandbox.save.json');s=await read();assert.equal(s.stage,5);assert.equal(s.planet.sandbox,true);assert.deepEqual(s.civilization,{version:1,entry:'legacy-stage5',completed:null});await act('journal');assert.match(await page.locator('.civilization-history').innerText(),/bez nového bonusu/);await page.locator('.civilization-history').scrollIntoViewIfNeeded();await shot('legacy-sandbox-1024');check('Historical stable stage5 sandbox stays accessible and receives no invented civic inheritance');
 assert.deepEqual(errors,[]);await writeFile(path.join(out,'result.json'),JSON.stringify({checks,errors,completion:complete,toolSample:{seconds,income,observed,expected:(income-.20)*seconds},nativeFrames:{count:frames.length,p50:[...frames].sort((a,b)=>a-b)[45],p95:[...frames].sort((a,b)=>a-b)[85],max:Math.max(...frames)},provenance:'Real J fixture and real paid pre-J branch imported unchanged. Native UI/RAF, no live setter. Historical sandbox is a separate compatibility check, not a fresh campaign.'},null,2));
}catch(e){await writeFile(path.join(out,'failure.json'),JSON.stringify({error:String(e),checks,errors,state:await read().catch(()=>null)},null,2));await shot('failure');console.error(e);process.exitCode=1;}finally{if(process.env.LUMAVORA_TRACE==='1')await context.tracing.stop({path:path.join(out,'trace.zip')});await browser.close();}
