/** P3 normal UI verification from an explicitly prepared-and-played P1/P2 export. */
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {createServer} from 'vite';
import {chromium} from 'playwright';
const output=path.resolve(process.env.PLANET_OUTPUT??'evidence/era-p3/browser');await mkdir(output,{recursive:true});
const url=new URL(process.env.LUMAVORA_URL??'http://127.0.0.1:5180');url.searchParams.set('test','1');
const ssr=await createServer({server:{middlewareMode:true,hmr:false,watch:null},appType:'custom',logLevel:'error'});const {parseGame}=await ssr.ssrLoadModule('/src/game/persistence.ts');
const source=path.resolve('tests/fixtures/saves/machines-restoration-completed.save.json');
await writeFile(path.join(output,'FIXTURE.md'),'# Targeted P3 browser verification\n\nImports the actually played P2 restoration scenario, itself based on a disclosed prepared P1 coast. P3 entry, movement, life contacts, tools, introductions, save/reload and ending use normal UI only. render_game_to_text is read-only; DEV advanceTime accelerates fixed-step simulation. No browser simulation writes. This is not a fresh 0→5 campaign or a human-duration measurement.\n');
const browser=await chromium.launch({headless:true,args:process.platform==='darwin'?['--use-gl=angle','--use-angle=metal']:[]}),context=await browser.newContext({viewport:{width:1536,height:960},acceptDownloads:true});if(process.env.LUMAVORA_TRACE==='1')await context.tracing.start({screenshots:true,snapshots:true,sources:true});const page=await context.newPage(),errors=[],timeline=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const read=()=>page.evaluate(()=>JSON.parse(window.render_game_to_text()));
async function frames(){for(let i=0;i<2;i++)await page.evaluate(()=>new Promise(r=>requestAnimationFrame(r)));}
async function action(name){timeline.push({action:name});await page.locator(`[data-action="${name}"]`).first().click();await frames();}
async function advance(ms){await page.evaluate(ms=>window.advanceTime(ms),ms);await frames();}
async function capture(name){await page.waitForTimeout(300);await page.screenshot({path:path.join(output,name+'.png')});await writeFile(path.join(output,name+'.json'),JSON.stringify(await read(),null,2));}
const active=s=>s.machines.fleet.find(u=>u.id===s.planet.activeMachine);
async function moveTo(pos,stop=2){for(let i=0;i<260;i++){const s=await read(),u=active(s),dx=pos.x-u.pos.x,dz=pos.z-u.pos.z,gap=Math.hypot(dx,dz);assert.equal(s.mode,'game');if(gap<=stop)return;const keys=[];if(Math.abs(dx)>.8)keys.push(dx>0?'d':'a');if(Math.abs(dz)>.8)keys.push(dz>0?'s':'w');for(const k of keys)await page.keyboard.down(k);await advance(gap>8?500:100);for(const k of keys)await page.keyboard.up(k);}throw new Error('Movement failed '+JSON.stringify({pos,unit:active(await read())}));}
async function waitFor(predicate,label,seconds=180){for(let i=0;i<seconds;i+=2){const s=await read();if(predicate(s))return s;assert.equal(s.mode,'game',label);await advance(2000);}throw new Error('Timed out '+label+' '+JSON.stringify((await read()).planet));}
async function exportState(name,reload=false){const before=await read();await action('pause');await action('saves');const [download]=await Promise.all([page.waitForEvent('download'),action('export')]);const file=path.join(output,name+'.save.json');await download.saveAs(file);const s=parseGame(await readFile(file,'utf8'));assert.deepEqual(s.planet,before.planet);if(reload){await page.locator('#import-save').setInputFiles(file);await frames();assert.deepEqual((await read()).planet,before.planet);}else await action('close');return s;}
try{
 await page.goto(url.href);await action('saves');await page.locator('#import-save').setInputFiles(source);await action('machine-next');let s=await read();assert.equal(s.stage,5);assert.equal(s.controlModel,'vehicle');const inherited=structuredClone(s.machines.blueprints),body=structuredClone(s.player),air=s.machines.fleet.find(u=>s.machines.blueprints.find(d=>d.id===u.blueprint).blueprint.carrier==='air');await action('planet-vehicle:'+air.id);await capture('01-entry');
 // Physically return to the nursery and obtain every missing contact.
 await moveTo(s.planet.nursery.pos);await action('planet-biome:0');s=await read();for(const source of s.planet.nursery.sources){const r=s.world.resources.find(r=>r.id===source.resourceId);await moveTo(r.pos);await action('planet-sample:culture:'+r.id);}
 const home=s.tribe.huts.find(h=>h.kind==='shelter').pos;
 for(const species of ['bell','gnaw','crest']){await moveTo(home);s=await read();const existing=s.world.creatures.find(c=>c.species===species&&Math.hypot(c.pos.x-s.planet.nursery.pos.x,c.pos.z-s.planet.nursery.pos.z)<12);if(!existing)await action('planet-nursery:'+species);s=await read();const c=s.world.creatures.filter(c=>c.species===species).sort((a,b)=>Math.hypot(a.pos.x-s.planet.nursery.pos.x,a.pos.z-s.planet.nursery.pos.z)-Math.hypot(b.pos.x-s.planet.nursery.pos.x,b.pos.z-s.planet.nursery.pos.z))[0];assert.ok(c);await moveTo(c.pos);await action('planet-sample:creature:'+c.id);}
 await capture('02-contacts');await exportState('contacts',true);s=await read();assert.deepEqual(s.player,body);assert.deepEqual(s.machines.blueprints,inherited);await action('planet-vehicle:'+air.id);
 // Raise climate using the actual inherited seeder, then measure regression.
 await action('planet-tool');await waitFor(s=>s.planet.tScore>=1,'first T1');await action('planet-tool');const radius=s=>Math.hypot(s.planet.temperature,s.planet.atmosphere),raised=radius(await read());await advance(90000);assert.ok(radius(await read())>raised+.1);assert.equal((await read()).planet.tScore,0);await capture('03-regression');await exportState('unstable',true);
 await action('planet-vehicle:'+air.id);await action('planet-tool');
 for(const biome of (await read()).planet.biomes){await moveTo(biome.pos);await action('planet-biome:'+biome.id);await waitFor(s=>s.planet.tScore>=biome.level,'T'+biome.level,300);for(const key of ['culture:6','culture:7','species:bell','species:gnaw','species:crest'])await action(`planet-introduce:${biome.id}:${key}`);s=await read();assert.equal(s.planet.stabilizers.filter(r=>r.biome===biome.id).length,2);assert.equal(s.planet.populations.filter(r=>r.biome===biome.id).length,3);await advance(8000);await capture('04-biome-'+biome.id);}
 await action('planet-tool');await action('planet-map');await waitFor(s=>s.mode==='won','planet finale',120);await capture('05-finale');await action('sandbox');assert.equal((await read()).planet.sandbox,true);await advance(120000);s=await read();assert.equal(s.planet.tScore,3);assert.equal(s.planet.toolOn,false);if(!(await read()).planetMap)await action('planet-map');await capture('06-stable-map');await exportState('stable-sandbox',true);await capture('07-reloaded');assert.deepEqual(errors,[]);
 await writeFile(path.join(output,'result.json'),JSON.stringify({status:'passed',tick:s.tick,planet:s.planet,errors,timeline},null,2));console.log(JSON.stringify({status:'passed',tick:s.tick,errors}));
}catch(error){await capture('failure').catch(()=>{});await writeFile(path.join(output,'failure.json'),JSON.stringify({message:error.message,state:await read().catch(()=>null),errors,timeline},null,2));throw error;}
finally{if(process.env.LUMAVORA_TRACE==='1')await context.tracing.stop({path:path.join(output,'trace.zip')});await browser.close();await ssr.close();}
